name: Build Static Site

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build static site
      run: bun run build
    
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push dist directory
      run: |
        # Get the current branch name
        BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        echo "Current branch: $BRANCH_NAME"
        
        # Checkout the branch (in case we're in detached HEAD)
        git checkout $BRANCH_NAME
        
        # Stage dist changes
        git add dist/
        
        # Commit and push if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update built static site
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          
          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push origin $BRANCH_NAME
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: static-site
        path: dist/